ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-9.1.5}

# ajouter des plugins supplémentaires ici
# exemple : RUN elasticsearch-plugin install analysis-icu

