ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-9.1.5}

# Ajoute les plugins kibana supplémentaires ici
# Exemple : RUN kibana-plugin install <name|url>
